#define IDI_SCREENSAVER                 100
#define IDS_APPNAME                     130
#define IDC_SLIDER_NUMOFSTARS           1000
#define IDC_SLIDER_INTERVAL             1001
#define IDC_TEXT_NUMOFSTARS             1002
#define IDC_TEXT_INTERVAL               1003
#define IDC_BUTTON_DEFAULT              1004
#define DLG_SCRNSAVECONFIGURE           2003
#define IDC_STATIC                      -1
#define IDC_COMBO_FONTNAME				101 
#define IDC_STATIC_FONT					102
#define IDC_COMBO_CLOCKFORMAT			103
#define IDC_STATIC_CLOCKFORMAT			104
#define IDC_STATIC_GRADIENTSTARTCOLOR	105
#define IDC_COLOR_GRADIENTSTARTCOLOR	106
#define IDC_STATIC_GRADIENTENDCOLOR		107
#define IDC_COLOR_GRADIENTENDCOLOR		108 
#define IDC_STATIC_FONTCOLOR			109 
#define IDC_COLOR_FONTCOLOR				110 



